# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SimpleContacts' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for SimpleContacts
  pod 'Masonry', '~> 1.1.0'
  pod 'EasyReact', '~> 2.3.1'
  pod 'SVProgressHUD', '~> 2.2.5'
  pod 'ReactiveObjC', '~> 3.1.1'

  target 'SimpleContactsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SimpleContactsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
